name = "AbstractCosmologicalEmulators"
uuid = "c83c1981-e5c4-4837-9eb8-c9b1572acfc6"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]
version = "0.2.0"

[deps]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"

[compat]
Lux = "0.5"
SimpleChains = "0.4"
julia = "1.7"
