name = "AbstractEmulator"
uuid = "0dc76ace-04b2-4bd9-b691-6d8501953659"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"

[compat]
LoopVectorization = "0.12"
SimpleChains = "0.4"
julia = "1.7"
