name = "AbstractCosmoEmulators"
uuid = "b49f2d86-bee3-412c-9739-7d6ab483f194"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"

[compat]
SimpleChains = "0.4"
julia = "1.7"
